spring:
  application:
    name: asset-box-consumer
  config:
    import: optional:file:.env.dev[.properties]
  mail:
    # 이메일 전송에 사용할 SMTP 서버의 호스트주소 ( Gmail의 SMTP 서버 )
    host: ${GOOGLE_SMTP_HOST}
    port: ${GOOGLE_SMTP_PORT} # SMTP 서버가 사용할 포트번호 : Gmail은 기본 STARTTLS를 사용하므로 587 설정
    # 이메일 전송에 사용할 Gmail 계정 사용자 & 비밀번호
    username: ${GOOGLE_SMTP_USERNAME}
    password: ${GOOGLE_SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          # STMP 인증 활성화
          auth: true
          # TLS 암호화 활성화 ( STARTTLS 암호화 사용하여 이메일 전송 시 데이터 보완 강화 )
          starttls:
            enable: true
          # SMTP 서버와 Timeout 설정 ( 밀리초 단위 )
          # 연결 시 Timeout
          connectiontimeout: 5000
          # 응답 대기 시 Timeout
          timeout: 5000
          # 데이터 전송 시 Timeout
          writetimeout: 5000
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    consumer:
      email-topic-group-id: email-topic-group
      enable-auto-commit: false
server:
  port: 8081

custom:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
